# 
# GitHub Actions workflow.
#
# Automatically deploys the "PlantHarvest" microservice on push.
#
name: Deploy PlantHarvest
run-name: ${{ github.actor }} is deploying using GitHub Actions ðŸš€
on:
  push:
    branches: 
      - main
    paths:
      - "PlantHarvest/**"
  pull_request:
    paths:
      - 'PlantHarvest/**'
  workflow_dispatch:

env:
  CONTAINER_APP_CONTAINER_NAME: plantharvestapi-container
  CONTAINER_APP_NAME: plantharvestapi-containerapp
  DOCKER_FILE_PATH: PlantHarvest/PlantHarvest.Api/Dockerfile
  PROJECT_NAME_FOR_DOCKER: plantharvestapi

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ðŸ This job's status is ${{ job.status }}."

  test:
    runs-on: ubuntu-latest

    env:
      mongodb-password: ${{ secrets.mongodb_password }}
      auth0-clientsecret: ${{ secrets.auth0_clientsecret }}

    needs: setup
    steps:
    # checkout the repo
    - name: Checkout to the branch
      uses: actions/checkout@v3

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: UnitTest
      run: dotnet test ~/work/GardenLog.V2023/GardenLog.V2023/Test/PlantHarvest.UnitTest/PlantHarvest.UnitTest.csproj -c Release --no-build

    - name: Test
      env:
        ASPNETCORE_ENVIRONMENT: Production
      run: dotnet test ~/work/GardenLog.V2023/GardenLog.V2023/Test/PlantHarvest.IntegrationTest/PlantHarvest.IntegrationTest.csproj -c Release --no-build
      
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    # checkout the repo
    - name: Checkout to the branch
      uses: actions/checkout@v3
      with:
        path: PlantHarvest

    - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
          ls ${{ github.workspace }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Deploy to containerapp
      uses: Azure/container-apps-deploy-action@v1
      with:
        containerAppName: ${{ env.CONTAINER_APP_CONTAINER_NAME }}
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
        acrName: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        acrUsername: ${{ secrets.REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
        imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        environmentVariables: mongodb-password=secretref:mongodb-password auth0-clientsecret=secretref:auth0-clientsecret
     # with:
     #   inlineScript: >
     #     az config set extension.use_dynamic_install=yes_without_prompt
     #
     #     az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --server ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
     # 
     #     az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }} --set-env-vars "mongodb-password=secretref:mongodb-password" "auth0-clientsecret=secretref:auth0-clientsecret"
     # - name: logout
     # run: >
     #   az logout

